/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-07 06:33:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class afterloginleft_005f1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>실시간 순위</title>\r\n");
      out.write("</head>\r\n");
      out.write("<link href=\"main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("        height: 100vh;\r\n");
      out.write("        background-image: url('goodnight.jpg');\r\n");
      out.write("        background-repeat : no-repeat center;\r\n");
      out.write("        background-size : cover;\r\n");
      out.write("        font-family: 'Jua', sans-serif;\r\n");
      out.write("		display:flex;\r\n");
      out.write("		justify-content:center;\r\n");
      out.write("		align-items:center;\r\n");
      out.write("		height:100%;\r\n");
      out.write("		color:white;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<header>실시간 순위입니다! 곡 제목과 가수, 앨범을 클릭하면 각각의 정보를 볼 수 있습니다! 노래는 음소거를 해제해서 들어주세요!</header>\r\n");
      out.write("<input type=\"checkbox\" id=\"menuicon\">\r\n");
      out.write("<label for=\"menuicon\">\r\n");
      out.write("	<span></span>\r\n");
      out.write("	<span></span>\r\n");
      out.write("	<span></span>\r\n");
      out.write("</label>\r\n");
      out.write("	<div class=\"sidebar\">\r\n");
      out.write("	<ul>\r\n");
      out.write("	<tr>\r\n");
      out.write("	<td>\r\n");
      out.write("	<br><br>\r\n");
      out.write("	<h1><a href=\"logout_Action.jsp\">로그아웃 하고 메인화면</a></h1>\r\n");
      out.write("	<br>\r\n");
      out.write("	<h1><a href=\"afterlogin.jsp\">다른 메뉴가기</a></h1>\r\n");
      out.write("	<br>\r\n");
      out.write("	</td>\r\n");
      out.write("	<td>\r\n");
      out.write("	<h1><a href=\"afterloginleft.jsp\">장르별 노래차트</a></h1> \r\n");
      out.write("	<br>\r\n");
      out.write("	<h3><a href=\"afterloginleft_1.jsp\">▷실시간 순위</a></h3> \r\n");
      out.write("	<br>\r\n");
      out.write("	<h3><a href=\"afterloginleft_2.jsp\">▷발라드</a></h3> \r\n");
      out.write("	<br>\r\n");
      out.write("	<h3><a href=\"afterloginleft_3.jsp\">▷랩/힙합</a></h3> \r\n");
      out.write("	<br>\r\n");
      out.write("	<h3><a href=\"afterloginleft_4.jsp\">▷트로트</a></h3> \r\n");
      out.write("	<br>\r\n");
      out.write("	<h3><a href=\"afterloginleft_5.jsp\">▷빌보드</a></h3> \r\n");
      out.write("	<br>\r\n");
      out.write("	<h1><a href=\"afterlogincenter.jsp\">음악공유 커뮤니티</a></h1> \r\n");
      out.write("	<br>\r\n");
      out.write("	<h1><a href=\"afterloginright.jsp\">오시는길</a></h1> \r\n");
      out.write("	<br>\r\n");
      out.write("	</td>\r\n");
      out.write("	</tr>\r\n");
      out.write("	</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<table class=\"type09\">\r\n");
      out.write("    <thead>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th scope=\"cols\">순위</th>\r\n");
      out.write("        <th scope=\"cols\">곡제목</th>\r\n");
      out.write("        <th scope=\"cols\">가수</th>\r\n");
      out.write("        <th scope=\"cols\">장르</th>\r\n");
      out.write("        <th scope=\"cols\">앨범</th>\r\n");
      out.write("        <th scope=\"cols\">듣기</th>\r\n");
      out.write("    </tr>\r\n");
      out.write("    </thead>\r\n");
      out.write("    <tbody>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th scope=\"row\">1위</th>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/track/51601987\">회전목마 (Feat. Zion.T, 원슈타인) (Prod. Slom)</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/artist/2684262\">sokodomo</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("			랩/힙합\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/album/6650319\">쇼미더머니 10 Episode 2</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<iframe src=\"https://www.youtube.com/embed/ZcGB8Yc_SlE?autoplay=1&mute=1\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th scope=\"row\">2위</th>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/track/51874035\">리무진 (Feat. MINO) (Prod. GRAY)</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("			<a href=\"https://vibe.naver.com/artist/3177930\">BE'O (비오)</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	랩/힙합\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("			<a href=\"https://vibe.naver.com/album/6706049\">쇼미더머니 10 Episode 3</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<iframe src=\"https://www.youtube.com/embed/3lwTql6YlSE\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    <tr>\r\n");
      out.write("        <th scope=\"row\">3위</th>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/track/51874036\">만남은 쉽고 이별은 어려워 (Feat. Leellamarz) (Prod. TOIL)</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/artist/107005\">베이식 (Basick)</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("			랩/힙합\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/album/6706049\">쇼미더머니 10 Episode 3</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<iframe src=\"https://www.youtube.com/embed/rY8_DRrQIvg\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th scope=\"row\">4위</th>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/track/51082248\">strawberry moon</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/artist/112579\">아이유(IU)</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("			락\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/album/6520837\">strawberry moon</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<iframe src=\"https://www.youtube.com/embed/sqgxcCjD04s?\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    <tr>\r\n");
      out.write("        <th scope=\"row\">5위</th>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/track/51524218\">Wake Up (Prod. 코드 쿤스트)</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/artist/32828\">개코</a>,\r\n");
      out.write("			<a href=\"https://vibe.naver.com/artist/2726674\">Ourealgoat (아우릴고트)</a>,\r\n");
      out.write("			<a href=\"https://vibe.naver.com/artist/2389301\">SINCE</a>,\r\n");
      out.write("			<a href=\"https://vibe.naver.com/artist/2905409\">안병웅</a>,\r\n");
      out.write("			<a href=\"https://vibe.naver.com/artist/2868769\">Tabber</a>,\r\n");
      out.write("			<a href=\"https://vibe.naver.com/artist/2933338\">조광일</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("			랩/힙합\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<a href=\"https://vibe.naver.com/album/6632981\">쇼미더머니 10 Episode 1</a>\r\n");
      out.write("        </td>\r\n");
      out.write("        <td>\r\n");
      out.write("        	<iframe src=\"https://www.youtube.com/embed/NHKn8Sny8xQ\" frameborder=\"0\" allow=\"accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture\" allowfullscreen></iframe>\r\n");
      out.write("        </td>\r\n");
      out.write("    </tr>\r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("    </tbody>\r\n");
      out.write("</table>\r\n");
      out.write("<footer>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
