/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.52
 * Generated at: 2021-12-09 10:11:35 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no\">\r\n");
      out.write("<title>민호랑 노래 듣자</title>\r\n");
      out.write("</head>\r\n");
      out.write("<style>\r\n");
      out.write("	* {margin:0;padding:0;}\r\n");
      out.write("	.section {}\r\n");
      out.write("	.section input[id*=\"slide\"] {display:none;}\r\n");
      out.write("\r\n");
      out.write("	.section .slide-wrap {max-width:1200px;margin:0 auto;}\r\n");
      out.write("	.section .slidelist {white-space:nowrap;font-size:0;overflow:hidden;}\r\n");
      out.write("	.section .slidelist > li {display:inline-block;vertical-align:middle;width:100%;transition:all .5s;}\r\n");
      out.write("	.section .slidelist > li > a {display:block;position:relative;}\r\n");
      out.write("	.section .slidelist > li > a img {width:100%;}\r\n");
      out.write("	.section .slidelist label {position:absolute;z-index:10;top:50%;transform:translateY(-50%);padding:50px;cursor:pointer;}\r\n");
      out.write("	.section .slidelist .left {left:30px;background:url('leftarrow.png') center center / 100% no-repeat;}\r\n");
      out.write("	.section .slidelist .right {right:30px;background:url('rightarrow.png') center center / 100% no-repeat;}\r\n");
      out.write("	.section .slidelist .textbox {position:absolute;z-index:1;top:50%;left:50%;transform:translate(-50%,-50%);line-height:1.6;text-align:center;}\r\n");
      out.write("	\r\n");
      out.write("	.section .slidelist .textbox h3 {font-size:50px;color:#fff;opacity:0;transform:translateY(30px);transition:all .5s;}\r\n");
      out.write("	.section .slidelist .textbox p {font-size:24px;color:#fff;opacity:0;transform:translateY(30px);transition:all .5s;}\r\n");
      out.write("\r\n");
      out.write("	.section input[id=\"slide01\"]:checked ~ .slide-wrap .slidelist > li {transform:translateX(0%);}\r\n");
      out.write("	.section input[id=\"slide02\"]:checked ~ .slide-wrap .slidelist > li {transform:translateX(-100%);}\r\n");
      out.write("	.section input[id=\"slide03\"]:checked ~ .slide-wrap .slidelist > li {transform:translateX(-200%);}\r\n");
      out.write("\r\n");
      out.write("	.section input[id=\"slide01\"]:checked ~ .slide-wrap li:nth-child(1) .textbox h3 {opacity:1;transform:translateY(0);transition-delay:.2s;}\r\n");
      out.write("	.section input[id=\"slide01\"]:checked ~ .slide-wrap li:nth-child(1) .textbox p {opacity:1;transform:translateY(0);transition-delay:.4s;}\r\n");
      out.write("	.section input[id=\"slide02\"]:checked ~ .slide-wrap li:nth-child(2) .textbox h3 {opacity:1;transform:translateY(0);transition-delay:.2s;}\r\n");
      out.write("	.section input[id=\"slide02\"]:checked ~ .slide-wrap li:nth-child(2) .textbox p {opacity:1;transform:translateY(0);transition-delay:.4s;}\r\n");
      out.write("	.section input[id=\"slide03\"]:checked ~ .slide-wrap li:nth-child(3) .textbox h3 {opacity:1;transform:translateY(0);transition-delay:.2s;}\r\n");
      out.write("	.section input[id=\"slide03\"]:checked ~ .slide-wrap li:nth-child(3) .textbox p {opacity:1;transform:translateY(0);transition-delay:.4s;}\r\n");
      out.write("</style>\r\n");
      out.write("<link href=\"main.css\" rel=\"stylesheet\" type=\"text/css\">\r\n");
      out.write("<body>\r\n");
      out.write("<header>민호랑 노래 듣자 사이트에 오신 것을 환영합니다! 사이트에 대한 정보는 화면 중간 메뉴 아이콘을 눌러주세요!</header>\r\n");
      out.write("<input type=\"checkbox\" id=\"menuicon\">\r\n");
      out.write("<label for=\"menuicon\">\r\n");
      out.write("	<span></span>\r\n");
      out.write("	<span></span>\r\n");
      out.write("	<span></span>\r\n");
      out.write("</label>\r\n");
      out.write("	<div class=\"sidebar\">\r\n");
      out.write("		<ul>\r\n");
      out.write("			<tr>\r\n");
      out.write("				<td>\r\n");
      out.write("				<br><br>\r\n");
      out.write("					<h1><a href=\"logout_Action.jsp\">메인화면</a></h1>\r\n");
      out.write("				<br>\r\n");
      out.write("				</td>\r\n");
      out.write("				<td>\r\n");
      out.write("					<h1>민호랑 노래 듣자 사이트에 오신 분들을 모두 환영합니다!</h1> \r\n");
      out.write("					<h3>서로 노래를 추천해 주며 공유를 하는 사이트입니다.</h3>\r\n");
      out.write("					<h3>이 사이트의 기능은 모두 로그인 후 사용가능합니다!</h3>\r\n");
      out.write("					<h3>사이트 중심의 로그인 창을 이용해 로그인을 해주세요!</h3>\r\n");
      out.write("					<h3>만약 계정이 없다면 회원가입을 해주세요!</h3>\r\n");
      out.write("				<br>\r\n");
      out.write("					<h3>만약 '이미 로그인이 되어있습니다.'라는 오류가 뜬다면 상단의 메인화면을 클릭해주세요!</h3>\r\n");
      out.write("				</td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("<div class=\"section\">\r\n");
      out.write("	<input type=\"radio\" name=\"slide\" id=\"slide01\" checked>\r\n");
      out.write("	<input type=\"radio\" name=\"slide\" id=\"slide02\">\r\n");
      out.write("	<input type=\"radio\" name=\"slide\" id=\"slide03\">\r\n");
      out.write("	<div class=\"slide-wrap\">\r\n");
      out.write("		<ul class=\"slidelist\">\r\n");
      out.write("			<li>\r\n");
      out.write("				<a>\r\n");
      out.write("					<label for=\"slide03\" class=\"left\"></label>\r\n");
      out.write("					<div class=\"textbox\">\r\n");
      out.write("						<h3>음악을 공유할 수 있습니다.</h3>\r\n");
      out.write("						<p>음악 공유 커뮤니티를 통해서 회원들끼리 음악을 공유합니다.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<img src=\"index1.jpg\">\r\n");
      out.write("					<label for=\"slide02\" class=\"right\"></label>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<a>\r\n");
      out.write("					<label for=\"slide01\" class=\"left\"></label>\r\n");
      out.write("					<div class=\"textbox\">\r\n");
      out.write("						<h3>음악 순위를 확인할 수 있습니다.</h3>\r\n");
      out.write("						<p>장르별 노래차트를 통해 음악 순위를 확인합니다.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<img src=\"index2.png\">\r\n");
      out.write("					<label for=\"slide03\" class=\"right\"></label>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li>\r\n");
      out.write("				<a>\r\n");
      out.write("					<label for=\"slide02\" class=\"left\"></label>\r\n");
      out.write("					<div class=\"textbox\">\r\n");
      out.write("						<h3>음악을 감상할 수 있습니다.</h3>\r\n");
      out.write("						<p>장르별 노래차트에서 음악을 감상합니다.</p>\r\n");
      out.write("					</div>\r\n");
      out.write("					<img src=\"index3.jpg\">\r\n");
      out.write("					<label for=\"slide01\" class=\"right\"></label>\r\n");
      out.write("				</a>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</div>\r\n");
      out.write("	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<section>\r\n");
      out.write("		\r\n");
      out.write("	<h1>로그인 후 이용하세요!</h1>\r\n");
      out.write("	<form method=\"post\" action=\"login_Action.jsp\">\r\n");
      out.write("		<div>\r\n");
      out.write("			<input type=\"text\" name=\"userID\"  maxlength=\"20\" placeholder=\"USER NAME\" required>\r\n");
      out.write("			<h4>USER NAME</h4>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div>\r\n");
      out.write("			<input type=\"password\"name=\"userPassword\" maxlength=\"20\" placeholder=\"PASSWORD\" required>\r\n");
      out.write("			<h4>PASSWORD</h4>\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"btn-area\">\r\n");
      out.write("			<button type=\"submit\">LOGIN</button>\r\n");
      out.write("		</div>\r\n");
      out.write("	</form>\r\n");
      out.write("	<div class=\"caption\">\r\n");
      out.write("		<a href=\"join.jsp\">회원가입 하시겠습니까?</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	</section>\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	<footer>");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
